name: BPMN Visualisatie naar GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Zoek BPMN-bestand in README
      id: find_bpmn
      run: |
        # Zoek naar een patroon in de README die het BPMN-bestand specificeert
        # Bijvoorbeeld: [BPMN](path/to/file.bpmn)
        BPMN_PATH=$(grep -oP '(?<=\]\().+\.bpmn(?=\))' README.md | head -n 1)
        echo "bpmn_path=$BPMN_PATH" >> $GITHUB_OUTPUT
        if [ -z "$BPMN_PATH" ]; then
          echo "Geen BPMN-bestand gevonden in README."
          exit 1
        fi

    - name: Kopieer BPMN-bestand naar deployment directory
      run: |
        mkdir -p deployment
        cp ${{ steps.find_bpmn.outputs.bpmn_path }} deployment/diagram.bpmn

    - name: Maak HTML-pagina met Zoom Controls
      run: |
        cat <<EOF > deployment/index.html
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8">
          <title>BPMN Visualisatie</title>
          <link rel="stylesheet" href="https://unpkg.com/bpmn-js@13.0.3/dist/assets/diagram-js.css">
          <link rel="stylesheet" href="https://unpkg.com/bpmn-js@13.0.3/dist/assets/bpmn-js.css">
          <style>
            body {
              font-family: Arial, sans-serif;
              margin: 20px;
            }
            #controls {
              margin-bottom: 10px;
            }
            #controls button {
              padding: 10px;
              margin-right: 5px;
              font-size: 16px;
            }
            #canvas {
              width: 100%;
              height: 600px;
              border: 1px solid #ccc;
            }
          </style>
        </head>
        <body>
          <h1>BPMN Diagram</h1>
          <div id="controls">
            <button id="zoom-in">Inzoomen</button>
            <button id="zoom-out">Uitzoomen</button>
            <button id="reset-zoom">Reset Zoom</button>
          </div>
          <div id="canvas"></div>
          <script src="https://unpkg.com/bpmn-js@13.0.3/dist/bpmn-viewer.development.js"></script>
          <script>
            fetch('diagram.bpmn')
              .then(response => response.text())
              .then(bpmnXML => {
                const container = document.getElementById('canvas');
                const viewer = new BpmnJS({ container });
                viewer.importXML(bpmnXML, function(err) {
                  if (err) {
                    console.error('Fout bij importeren BPMN:', err);
                  } else {
                    viewer.get('canvas').zoom('fit-viewport');
                  }
                });

                // Zoom In knop
                document.getElementById('zoom-in').addEventListener('click', () => {
                  const currentZoom = viewer.get('canvas').zoom();
                  viewer.get('canvas').zoom(currentZoom * 1.2);
                });

                // Zoom Out knop
                document.getElementById('zoom-out').addEventListener('click', () => {
                  const currentZoom = viewer.get('canvas').zoom();
                  viewer.get('canvas').zoom(currentZoom / 1.2);
                });

                // Reset Zoom knop
                document.getElementById('reset-zoom').addEventListener('click', () => {
                  viewer.get('canvas').zoom('fit-viewport');
                });
              })
              .catch(error => {
                console.error('Fout bij het laden van BPMN-bestand:', error);
              });
          </script>
        </body>
        </html>
        EOF

    - name: Configureer GitHub Pages
      uses: actions/configure-pages@v4
      with:
        build_dir: deployment

    - name: Upload artefacten
      uses: actions/upload-pages-artifact@v1
      with:
        path: deployment

    - name: Deploy naar GitHub Pages
      uses: actions/deploy-pages@v1
