name: Generate BPMN PNG and Update README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-png:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # Voorkomt dat GITHUB_TOKEN automatisch wordt gebruikt voor pushes

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Find BPMN file path in README
      id: find_bpmn
      run: |
        # Zoek naar een BPMN-bestand link in README.md, bijvoorbeeld [BPMN](path/to/file.bpmn)
        BPMN_PATH=$(grep -oP '(?<=\]\().+\.bpmn(?=\))' README.md | head -n 1)
        echo "bpmn_path=$BPMN_PATH" >> $GITHUB_OUTPUT
        if [ -z "$BPMN_PATH" ]; then
          echo "Geen BPMN-bestand gevonden in README."
          exit 1
        fi

    - name: Generate PNG from BPMN via Kroki
      env:
        BPMN_PATH: ${{ steps.find_bpmn.outputs.bpmn_path }}
      run: |
        # Controleer of het BPMN-bestand bestaat
        if [ ! -f "$BPMN_PATH" ]; then
          echo "Het BPMN-bestand '$BPMN_PATH' bestaat niet."
          exit 1
        fi

        # Gebruik de Kroki API om het BPMN-diagram om te zetten naar PNG
        curl -X POST \
          -H "Content-Type: text/plain" \
          --data-binary "@$BPMN_PATH" \
          https://kroki.io/bpmn/png \
          --output diagram.png

        # Controleer of de PNG correct is gegenereerd
        if [ ! -f diagram.png ]; then
          echo "Fout bij het genereren van diagram.png via Kroki."
          exit 1
        fi

    - name: Update README with PNG
      run: |
        # Definieer het pad naar de afbeelding, bijvoorbeeld 'images/diagram.png'
        IMAGE_PATH="images/diagram.png"

        # Maak de images directory als deze nog niet bestaat
        mkdir -p images

        # Verplaats de gegenereerde PNG naar de images directory
        mv diagram.png "$IMAGE_PATH"

        # Controleer of de sectie "## BPMN Diagram" al bestaat
        if grep -q "## BPMN Diagram" README.md; then
          # Verwijder alles na "## BPMN Diagram" om de afbeelding te vervangen
          sed -i '/## BPMN Diagram/q' README.md
        fi

        # Voeg de "## BPMN Diagram" sectie toe met de PNG afbeelding
        echo -e "\n## BPMN Diagram\n\n![BPMN Diagram]($IMAGE_PATH)" >> README.md

    - name: Commit changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add images/diagram.png README.md
        git commit -m "Generate BPMN diagram PNG and update README [skip ci]" || echo "Geen wijzigingen om te committen"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: main
